name: WayStone
version: '1.0'
main: com.minegolem.wayStone.WayStone
api-version: '1.21'
authors: [ WorkWolf_2 ]
commands:
  waystonesee:
    permission: waystone.admin.see
    usage: /<command> <player>
  waystonegive:
    permission: waystone.admin.give
    usage: /<command>
