CREATE TABLE IF NOT EXISTS waystones (
   id INT AUTO_INCREMENT PRIMARY KEY,
   player_uuid VARCHAR(36) NOT NULL,
   name VARCHAR(100) NOT NULL,
   world VARCHAR(50) NOT NULL,
   x INT NOT NULL,
   y INT NOT NULL,
   z INT NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);